<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQDDdtLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nQDDdtL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nQDDdtL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'news' => ['privates', '.errored..service_locator.nQDDdtL.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.nQDDdtL": it needs an instance of "App\\Entity\\News" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'news' => 'App\\Entity\\News',
        ]);
    }
}
