<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_96wQ8SZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.96wQ8SZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.96wQ8SZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\LoginController::redirectAction' => ['privates', '.service_locator.uBR2pyw.App\\Controller\\LoginController::redirectAction()', 'getLoginControllerredirectActionService', true],
            'App\\Controller\\NewsController::delete' => ['privates', '.service_locator.nQDDdtL.App\\Controller\\NewsController::delete()', 'getNewsControllerdeleteService', true],
            'App\\Controller\\NewsController::edit' => ['privates', '.service_locator.nQDDdtL.App\\Controller\\NewsController::edit()', 'getNewsControllereditService', true],
            'App\\Controller\\NewsController::index' => ['privates', '.service_locator.WUzs2TX.App\\Controller\\NewsController::index()', 'getNewsControllerindexService', true],
            'App\\Controller\\NewsController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\NewsController::new()', 'getNewsControllernewService', true],
            'App\\Controller\\NewsController::show' => ['privates', '.service_locator.q9gYYmg.App\\Controller\\NewsController::show()', 'getNewsControllershowService', true],
            'App\\Controller\\PhoneController::admin_dashboard' => ['privates', '.service_locator.nbonErD.App\\Controller\\PhoneController::admin_dashboard()', 'getPhoneControlleradminDashboardService', true],
            'App\\Controller\\PhoneController::delete' => ['privates', '.service_locator.kipcCHB.App\\Controller\\PhoneController::delete()', 'getPhoneControllerdeleteService', true],
            'App\\Controller\\PhoneController::edit' => ['privates', '.service_locator.smI6zOw.App\\Controller\\PhoneController::edit()', 'getPhoneControllereditService', true],
            'App\\Controller\\PhoneController::member_home' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PhoneController::member_home()', 'getPhoneControllermemberHomeService', true],
            'App\\Controller\\PhoneController::new' => ['privates', '.service_locator.Ji5OBMP.App\\Controller\\PhoneController::new()', 'getPhoneControllernewService', true],
            'App\\Controller\\PhoneController::show' => ['privates', '.service_locator.Dqjx1.5.App\\Controller\\PhoneController::show()', 'getPhoneControllershowService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4b92lv..App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\LoginController:redirectAction' => ['privates', '.service_locator.uBR2pyw.App\\Controller\\LoginController::redirectAction()', 'getLoginControllerredirectActionService', true],
            'App\\Controller\\NewsController:delete' => ['privates', '.service_locator.nQDDdtL.App\\Controller\\NewsController::delete()', 'getNewsControllerdeleteService', true],
            'App\\Controller\\NewsController:edit' => ['privates', '.service_locator.nQDDdtL.App\\Controller\\NewsController::edit()', 'getNewsControllereditService', true],
            'App\\Controller\\NewsController:index' => ['privates', '.service_locator.WUzs2TX.App\\Controller\\NewsController::index()', 'getNewsControllerindexService', true],
            'App\\Controller\\NewsController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\NewsController::new()', 'getNewsControllernewService', true],
            'App\\Controller\\NewsController:show' => ['privates', '.service_locator.q9gYYmg.App\\Controller\\NewsController::show()', 'getNewsControllershowService', true],
            'App\\Controller\\PhoneController:admin_dashboard' => ['privates', '.service_locator.nbonErD.App\\Controller\\PhoneController::admin_dashboard()', 'getPhoneControlleradminDashboardService', true],
            'App\\Controller\\PhoneController:delete' => ['privates', '.service_locator.kipcCHB.App\\Controller\\PhoneController::delete()', 'getPhoneControllerdeleteService', true],
            'App\\Controller\\PhoneController:edit' => ['privates', '.service_locator.smI6zOw.App\\Controller\\PhoneController::edit()', 'getPhoneControllereditService', true],
            'App\\Controller\\PhoneController:member_home' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PhoneController::member_home()', 'getPhoneControllermemberHomeService', true],
            'App\\Controller\\PhoneController:new' => ['privates', '.service_locator.Ji5OBMP.App\\Controller\\PhoneController::new()', 'getPhoneControllernewService', true],
            'App\\Controller\\PhoneController:show' => ['privates', '.service_locator.Dqjx1.5.App\\Controller\\PhoneController::show()', 'getPhoneControllershowService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4b92lv..App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\LoginController::redirectAction' => '?',
            'App\\Controller\\NewsController::delete' => '?',
            'App\\Controller\\NewsController::edit' => '?',
            'App\\Controller\\NewsController::index' => '?',
            'App\\Controller\\NewsController::new' => '?',
            'App\\Controller\\NewsController::show' => '?',
            'App\\Controller\\PhoneController::admin_dashboard' => '?',
            'App\\Controller\\PhoneController::delete' => '?',
            'App\\Controller\\PhoneController::edit' => '?',
            'App\\Controller\\PhoneController::member_home' => '?',
            'App\\Controller\\PhoneController::new' => '?',
            'App\\Controller\\PhoneController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\LoginController:redirectAction' => '?',
            'App\\Controller\\NewsController:delete' => '?',
            'App\\Controller\\NewsController:edit' => '?',
            'App\\Controller\\NewsController:index' => '?',
            'App\\Controller\\NewsController:new' => '?',
            'App\\Controller\\NewsController:show' => '?',
            'App\\Controller\\PhoneController:admin_dashboard' => '?',
            'App\\Controller\\PhoneController:delete' => '?',
            'App\\Controller\\PhoneController:edit' => '?',
            'App\\Controller\\PhoneController:member_home' => '?',
            'App\\Controller\\PhoneController:new' => '?',
            'App\\Controller\\PhoneController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
