<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WUzs2TX.App\Controller\NewsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WUzs2TX.App\\Controller\\NewsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
        ], [
            'newsRepository' => 'App\\Repository\\NewsRepository',
        ]))->withContext('App\\Controller\\NewsController::index()', $container);
    }
}
