<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nQDDdtL.App\Controller\NewsController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.nQDDdtL'] ?? $container->load('get_ServiceLocator_NQDDdtLService'));

        if (isset($container->privates['.service_locator.nQDDdtL.App\\Controller\\NewsController::delete()'])) {
            return $container->privates['.service_locator.nQDDdtL.App\\Controller\\NewsController::delete()'];
        }

        return $container->privates['.service_locator.nQDDdtL.App\\Controller\\NewsController::delete()'] = $a->withContext('App\\Controller\\NewsController::delete()', $container);
    }
}
