<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Dqjx1.5.App\Entity\Phone' shared service.
     *
     * @return \App\Entity\Phone
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Dqjx1.5": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".');
    }
}
