<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ji5OBMP.App\Controller\PhoneController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ji5OBMP.App\\Controller\\PhoneController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoneRepository' => ['privates', 'App\\Repository\\PhoneRepository', 'getPhoneRepositoryService', true],
        ], [
            'phoneRepository' => 'App\\Repository\\PhoneRepository',
        ]))->withContext('App\\Controller\\PhoneController::new()', $container);
    }
}
