<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kipcCHB.App\Controller\PhoneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kipcCHB.App\\Controller\\PhoneController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phone' => ['privates', '.errored..service_locator.kipcCHB.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.kipcCHB": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".'],
            'phoneRepository' => ['privates', 'App\\Repository\\PhoneRepository', 'getPhoneRepositoryService', true],
        ], [
            'entityManager' => '?',
            'phone' => 'App\\Entity\\Phone',
            'phoneRepository' => 'App\\Repository\\PhoneRepository',
        ]))->withContext('App\\Controller\\PhoneController::delete()', $container);
    }
}
