<?php

namespace ContainerQkL1FAh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dqjx1.5.App\Controller\PhoneController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dqjx1.5.App\\Controller\\PhoneController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phone' => ['privates', '.errored..service_locator.Dqjx1.5.App\\Entity\\Phone', NULL, 'Cannot autowire service ".service_locator.Dqjx1.5": it needs an instance of "App\\Entity\\Phone" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phone' => 'App\\Entity\\Phone',
        ]))->withContext('App\\Controller\\PhoneController::show()', $container);
    }
}
