<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2JIDnm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2JIDnm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2JIDnm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2JIDnm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2JIDnm\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2JIDnm',
    'container.build_id' => '4e8ace2a',
    'container.build_time' => 1718188299,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2JIDnm');
