<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAgTy53P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAgTy53P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAgTy53P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAgTy53P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAgTy53P\App_KernelDevDebugContainer([
    'container.build_hash' => 'AgTy53P',
    'container.build_id' => '336e7064',
    'container.build_time' => 1718198001,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAgTy53P');
